### ISSUE TITLE
Ldk-Server Milestone 2

### ISSUE THREAD

**Issue by G8XSU** [lightningdevkit/ldk-server#10]
* Following Apis:
    - [x]  - /getNodeId (https://github.com/lightningdevkit/ldk-node-server/pull/13)
    - [x]  - /getNodeStatus (https://github.com/lightningdevkit/ldk-node-server/pull/13)
    - [x]     - /onchain/send   (Moved from milestone-3) (https://github.com/lightningdevkit/ldk-node-server/pull/5)
    - [x]     - /bolt12/receive   (Moved from milestone-3) (https://github.com/lightningdevkit/ldk-node-server/pull/5)
    - [x]     - /bolt12/send  (Moved from milestone-3) (https://github.com/lightningdevkit/ldk-node-server/pull/5)
    - [x]     - List channels (Moved from milestone-3) (https://github.com/lightningdevkit/ldk-node-server/pull/13)
    - [x]     - /listPaymentsHistory (Moved from milestone-3) (https://github.com/lightningdevkit/ldk-node-server/pull/15)
    - [x]     - /getPaymentDetails (Moved from milestone-3) (https://github.com/lightningdevkit/ldk-node-server/pull/15)
    - [x]     - Edit fees api  (Moved from milestone-3) (https://github.com/lightningdevkit/ldk-node-server/pull/16)
    - [x]     - LDK-node / LDK upgrade. (#18)

  
- [x] Error handling for all apis. (https://github.com/lightningdevkit/ldk-node-server/pull/19, https://github.com/lightningdevkit/ldk-node-server/pull/20) (https://github.com/lightningdevkit/ldk-server/pull/46)
- [x] Integrate BitcoinD support (https://github.com/lightningdevkit/ldk-node/pull/370, https://github.com/lightningdevkit/ldk-node-server/pull/21)
- [x] Some parts of storing forwarding payments but not feature complete maybe.
