### ISSUE TITLE
Ldk-Server Milestone 3

### ISSUE THREAD

**Issue by G8XSU** [lightningdevkit/ldk-server#11]
- [x] * Support storing Forwarding payments in ldk-node/ldk-server. (Moved from Milestone-2)
  - [x]   * https://github.com/lightningdevkit/ldk-node/pull/404
  - [x]   * https://github.com/lightningdevkit/ldk-node-server/pull/22
  - [x]   * https://github.com/lightningdevkit/ldk-server/pull/23
  - [x]   * Start storing forwarded payments in ldk-server (ldk-node release required) (https://github.com/lightningdevkit/ldk-server/pull/32)
- [x]   * ListForwardedPayments API proto and impl. (https://github.com/lightningdevkit/ldk-server/pull/32)
- [x] *  /getNodeBalances https://github.com/lightningdevkit/ldk-server/pull/26
- [x] * Config support https://github.com/lightningdevkit/ldk-server/pull/28
- [x] * Log facade ? (Blocked on ldk-node changes and release, prioritized for later.) (https://github.com/lightningdevkit/ldk-node/pull/407)(https://github.com/lightningdevkit/ldk-server/pull/44)

* Dockerize (not needed if we don't use postgres i think, since it can be run using just cargo run)
